ci: do source code repo reset after artifacts downloaded
in https://gito.corp.nucleisys.com/software/devtools/riscv-gnu-toolchain/-/jobs/231171/raw

Observed repo downloaded and extracted from artifacts

the source code show modified like this

HEAD detached at 3476734
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
	modified:   qemu (modified content)
	modified:   spike (modified content

submodule is not clean as expected

Entering 'qemu'
HEAD detached at b67b00e6
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   include/qemu/atomic.h
	modified:   include/qemu/compiler.h

no changes added to commit (use "git add" and/or "git commit -a")
Entering 'spike'
HEAD detached at a0298a3
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   fesvr/option_parser.cc

Signed-off-by: Huaqi Fang <578567190@qq.com>

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -109,10 +109,28 @@ prepare_source:
       - "*.log"
       - "*.env"
   before_script:
-    # check repo status
-    - git status || true
-    - git submodule || true
-    - git submodule foreach git status || true
+    # check toolchain repo status
+    - |
+        git status || true
+        git submodule || true
+        git submodule foreach git status || true
+        # force reset repo and its submodule source code
+        git reset --hard || true
+        git submodule foreach git reset --hard || true
+        git submodule foreach git status || true
+        echo "INFO: toolchain repo is ready!"
+    # check libncrt repo status
+    - |
+        if [ ! -d libncrt ] ; then
+            echo "ERROR: libncrt repo doesn't exist, exit now!"
+            exit 1
+        fi
+        pushd libncrt
+        git reset --hard || true
+        git submodule foreach git reset --hard || true
+        git submodule || true
+        popd
+        echo "INFO: libncrt repo is ready!"
     # set the toolver to branch name or tag name, see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
     - export citoolver=${CI_COMMIT_REF_SLUG}${CI_MERGE_REQUEST_PROJECT_ID}
     - echo "Build for toolchain version $citoolver, toolchain type $citooltype"
